baseurl = "/"
languageLang = "en"
languageCode = "en-us"
title = "Military Pay Charts, Benefits and More"
[permalinks]
  blog = "/:slug/"
  page = "/:slug/"
  bases = "/:slug/"
  army = "/:slug/"
  air-force = "/:slug/"
  marines = "/:slug/"
  navy = "/:slug/"
  tricare = "/:slug/"
  veterans = "/:slug/"
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5


