baseurl = "/"
languageCode = "en-us"
title = "Military Hacks"
[permalinks]
  blog = "/:slug/"
  page = "/:slug/"
  bases = "/:slug/"
  army = "/:slug/"
  air-force = "/:slug/"
  marines = "/:slug/"
  navy = "/:slug/"
  tricare = "/:slug/"
  veterans = "/:slug/"
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = true

